title: Introducción alñ PLN - 750108M - 2018-2
description: Universidad del Valle, Cali
sitename: Introducción al PLN
baseurl: '/750108M-II2018'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
